blog210103/urls.py
# from datetime import datetime

from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.views import static
import xadmin
from users import views
from django.views.static import serve


    # return HttpResponse('html2')
# def home(request):
#     t = get_template("index.html")
#     html = t.render(Context({
#         "template_dir":settings.TEMPLATE_DIRS[0],
#         "title":"Home",
#         "static_dir":settings.STATIC_ROOT}))
#     return HttpResponse(html)

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', xadmin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^$', views.index, name='user_center'),
    url(r'^$', views.index, name='user_logout'),
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^comment/(?P<art_id>.*)$', views.comment, name='user_comment'),
    url(r'^detail/(?P<art_id>.*)$', views.detail, name='detail'),
    url(r'^search/$', views.search, name='search'),
    url(r'^list/(?P<path>.*)$', views.list_web, name='list'),
    url(r'static/(?P<path>.*)$',static.serve,{'document_root': settings.STATIC_ROOT},name='static'),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT},name='media')
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/users/models.py
from django import forms
from django.contrib.auth.models import AbstractUser
from django.db import models
from DjangoUeditor.models import UEditorField
# from datetime import datetime



class Zuozhe(models.Model):
    zuozheNo = models.CharField(max_length=15, verbose_name='作者编号', null=False, blank=False)
    name = models.CharField(max_length=20, verbose_name='作者姓名', null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta():
        db_table = 'zuozhe'
        verbose_name = '作者管理'
        verbose_name_plural = verbose_name

class Category(models.Model):
    name = models.CharField(max_length=15,verbose_name='类别名')
    add_time = models.DateTimeField(verbose_name='生成日期', auto_now_add=True, null=True, blank=True)
    is_tab = models.BooleanField(verbose_name='是否显示',default=True)
    title = models.CharField(max_length=15,verbose_name='题目',default='')
    path_name = models.CharField(max_length=15,verbose_name='种类别名')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        verbose_name = '类别'
        verbose_name_plural = verbose_name

class TagInfo(models.Model):
    name = models.CharField(max_length=15,verbose_name='标签名')
    add_time = models.DateTimeField(auto_now_add=True,null=True,blank=True,verbose_name='生成日期')
    category = models.ForeignKey(Category,null=True,blank=True,verbose_name='类别')
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'taginfo'
        verbose_name ='标签'
        verbose_name_plural = verbose_name


class Article(models.Model):
    title = models.CharField(max_length=30, verbose_name='文章名', null=False, blank=False)
    # content = models.TextField(verbose_name='内容', default='')
    content = UEditorField(verbose_name='内容', width=600, height=300, toolbars="full",
                                  imagePath="course/ueditor/", filePath="course/ueditor/",
                                  upload_settings={"imageMaxSize": 1204000},default='')
    sort = models.IntegerField(verbose_name='顺序', default=0)
    click_num = models.IntegerField(default=0, verbose_name='点击量')
    zuozhe = models.ForeignKey(Zuozhe, null=True, blank=True,verbose_name='作者')  # ,related_name='id'
    check_status = models.IntegerField(default=0,verbose_name='审核状态',choices=((0,'审核中'),(1,'审核通过'),(2,'审核失败')))
    add_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间') #default=datetime.now,
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')
    image = models.TextField(verbose_name='图片',default="static/images/timg.jpg")
    category = models.ForeignKey(Category, null=True, blank=True, verbose_name='文章类别')
    tagInfo = models.ForeignKey(TagInfo, null=True, blank=True, verbose_name='文章标签')
    desc = models.TextField(verbose_name='文章简介', default='')
    is_recommend = models.BooleanField(verbose_name='是否推荐', default=False)

    def __str__(self):
        return self.title

    class Meta():
        db_table = 'article'
        verbose_name = '文章表'
        verbose_name_plural = verbose_name


class Pic(models.Model):
    pic_name = models.CharField(max_length=15,verbose_name='用户名')
    xuhao = models.IntegerField(verbose_name='xuhao',default=0)
    pic_path = models.TextField(verbose_name='图片路径', null=True, blank=True)
    create_time = models.DateTimeField(verbose_name='生成日期',auto_now_add=True,null=True,blank=True)
    modify_time = models.DateTimeField(verbose_name='修改日期',auto_now=True,null=True,blank=True)

    def __str__(self):
        return self.pic_name

    class Meta:
        db_table = 'roll_pic'
        verbose_name = '轮播图管理'
        verbose_name_plural = verbose_name

class User(models.Model):
    username = models.CharField(max_length=15, verbose_name='用户名',null=True,blank=True)
    password = models.CharField(max_length=50, verbose_name='密码',null=True,blank=True)
    nick_name = models.CharField(max_length=30,verbose_name='昵称',null=True,blank=True)
    email = models.CharField(max_length=30, verbose_name='邮箱',null=True,blank=True)
    image = models.ImageField(upload_to='user/upload/', verbose_name='头像图片',null=True,blank=True)
    addtime = models.DateTimeField(verbose_name='生成日期',auto_now_add=True,null=True,blank=True)
    # modify_time = models.DateTimeField(verbose_name='修改日期',auto_now=True,null=True,blank=True)
    is_start = models.BooleanField(default=False, verbose_name='激活')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容', null=True, blank=True)
    add_time = models.DateTimeField(auto_now_add=True,null=True,blank=True,verbose_name='生成日期')
    comment_man = models.ForeignKey(User,null=True,blank=True,verbose_name='用户名')
    article = models.ForeignKey(Article,null=True,blank=True,verbose_name='评论的文章')

    def __str__(self):
        return self.content

    class Meta:
        db_table = 'comment'
        verbose_name = '评论'
        verbose_name_plural = verbose_name


    # def __str__(self):
    #     return self.nick_name
    # class Meta:
    #     db_table = 'comment'
    #     verbose_name = '表单验证'
    #     verbose_name_p

# class UserProfile(AbstractUser):
#     nick_name = models.CharField(max_length=15,verbose_name='用户名')
#     # image = models.ImageField(upload_to='user/upload/', verbose_name='头像图片')
#     addtime = models.DateTimeField(verbose_name='生成日期',auto_now_add=True,null=True,blank=True)
#     # modify_time = models.DateTimeField(verbose_name='修改日期',auto_now=True,null=True,blank=True)
#     is_start = models.BooleanField(default=False, verbose_name='激活')
#
#     def __str__(self):
#         return self.username
#
#     class Meta:
#         # db_table = 'userprofile'
#         verbose_name = '用户表'
#         verbose_name_plural = verbose_name

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/index.html
{% extends 'base.html' %}
{% block title %}python,python爬虫教程,python深度学习,机器学习,python数据挖掘分析_Debug5_官方网站{% endblock %}
{% block content %}
    <div class="content">
        <div id="focusslide" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#focusslide" data-slide-to="0" class="active"></li>
                <li data-target="#focusslide" data-slide-to="1"></li>
                <li data-target="#focusslide" data-slide-to="2"></li>
            </ol>
             <div class="carousel-inner" role="listbox">

                    <div class="item active">
                        <a href="#" target="_blank" title="python爬虫教程">
                            <img src="/static/images/202008122338.jpg" alt="python爬虫教程" class="img-responsive"></a>
                    </div>
                    <div class="item">
                        <a href="#" target="_blank" title="tornado异步非阻塞教程">
                            <img src="/static/images/202008122347.jpg" alt="tornado异步非阻塞教程"
                                 class="img-responsive"></a>
                    </div>
                    <div class="item">
                        <a href="#" target="_blank" title="python学习">
                            <img src="/static/images/202008102025.jpg" alt="python"
                                 class="img-responsive"></a>
                    </div>

             </div>
<!--
                <div class="item active">
                    <a href="http://www.debug5.com/detail/480/" target="_blank" title="python爬虫教程">
                        <img src="/static/images/202008122338.jpg" alt="python爬虫教程" class="img-responsive"></a>
                </div>
                <div class="item">
                    <a href="http://www.debug5.com/detail/454/" target="_blank" title="tornado异步非阻塞教程">
                        <img src="/static/images/202008122347.jpg" alt="tornado异步非阻塞教程"
                             class="img-responsive"></a>
                </div>
                <div class="item">
                    <a href="#" target="_blank" title="python学习">
                        <img src="/static/images/202008102025.jpg" alt="python"
                             class="img-responsive"></a>
                </div>

-->

            <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
                    class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide"
                                                       role="button" data-slide="next" rel="nofollow"> <span
                class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span
                class="sr-only">下一个</span> </a>
        </div>
        {% for art in recommend_article %}
            <article class="excerpt-minic excerpt-minic-index">
                <h2><span class="red">【推荐】</span><a target="_blank" href="{% url 'detail' art.id %}"
                                                    title="{{art.title}}">{{ art.title }}</a>
                </h2>
                <p class="note">{{ art.desc }}</p>
            </article>
        {% endfor %}
        <div class="title">
            <h3>最新发布{{ BASE_DIR }} vv  {{ MEDIA_URL }}</h3>
            <div class="more">
                {% for cate in new_category %}
                <a href="#" title="{{ cate.name }}">{{ cate.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% for art in all_articles %}
            <article class="excerpt excerpt-1" style="">
                <a class="focus" href="{% url 'detail' art.id %}" title="{{ art.title }}" target="_blank"><img class="thumb"
                                                                                              data-original="{{ MEDIA_URL }}{{ art.image }}"
                                                                                              src="{{ MEDIA_URL }}{{ art.image }}"
                                                                                              alt="{{ art.title }}"
                                                                                              style="display: inline;"></a>
                <header><a class="cat" href="{% url 'list' art.category.path_name %}" title="{{ art.category.name }}" target="_blank">{{ art.category.name }}<i></i></a>
                    <h2><a href="{% url 'detail' art.id %}" title="{{ art.title }}" target="_blank">{{ art.title }}{{ MEDIA_URL }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <time class="time"><i class="glyphicon glyphicon-time"></i> {{ art.add_time }}</time>
                    <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ art.click_num }}</span> <a class="comment"
                                                                                                   href="##comment"
                                                                                                   title="评论"
                                                                                                   target="_blank"><i
                        class="glyphicon glyphicon-comment"></i> {{ art.comment_set.count }}</a>
                </p>
               <p class="note">{{ art.desc }}</p>
            </article>

        {% endfor %}
    {% include 'pagenation.html' %}
    </div>
    {% block Tag %}
            <div class="widget widget_sentence">
                <h3>标签云首页</h3>
                <div class="widget-sentence-content">
                    <ul class="plinks ptags">
{#                        直接 管道符 进行切片 和 倒序#}
                        {% for cate in cate_name|slice:':20:-1' %}
                        <li><a href="{% url 'list' cate.path_name %}" title="{{ cate.name }}"
                               draggable="false">{{ cate.name }} <span
                                class="badge">{{ cate.article_set.count }}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endblock %}
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block title %}{{ cate_obj.title }}_Debug5_官方网站{% endblock %}
{% block content %}
    <div class="content">
        <div class="title">
            <h3 style="line-height: 1.3">{{ cate_obj.name }}主题</h3>
        </div>

        {% for art in all_articles %}
            <article class="excerpt excerpt-{{ forloop.counter }}"><a class="focus" href="{% url 'detail' art.id %}"
                                                                      title="{{ art.title }}" target="_blank"><img
                    class="thumb" data-original="{{ MEDIA_URL }}{{ art.image }}"
                    src="{{ MEDIA_URL }}{{ art.image }}" alt="{{ art.title }}"
                    style="display: inline;"></a>
                <header><a class="cat" href="#" title="{{ cate_obj.name }}">{{ cate_obj.name }}<i></i></a>
                    <h2><a href="{% url 'detail' art.id %}" title="{{ art.title }}" target="_blank">{{ art.title }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <time class="time"><i class="glyphicon glyphicon-time"></i> {{ art.add_time }}</time>
                    <span class="views"><i class="glyphicon glyphicon-eye-open"></i>{{ art.click_num }}</span> <a
                        class="comment"
                        href="##comment"
                        title="评论"
                        target="_blank"><i
                        class="glyphicon glyphicon-comment"></i>{{ art.cont_num }}</a></p>
                <p class="note">{{ art.desc }}{{ BASE_DIR }}</p>
            </article>
        {% endfor %}

        <div class="row">
    <div class="col-lg-12">
        <!--<span class="pagination_count" style="line-height: 40px;">共{{ pages.total }}条记录 | 每页{{pages.page_size}}条</span>-->
        <ul class="pagination pagination-lg   pull-right" style="margin: 0 0 ;">
            {% if pages.is_prev == 1 %}
             <li>
                 <a href="{{ pages.url }}?&p=1" ><span>首页</span></a>
             </li>
            {%  endif %}

            {% for idx in pages.range %}
                {% if idx == pages.current %}
                    <li class="active"><a href="javascript:void(0);">{{ idx }}</a></li>
                {% else %}
                    <li><a href="{{ pages.url }}?&p={{idx}}&tag={{tagnum}}&keyword={{ cont }}">{{ idx }}</a></li>
                {% endif %}
            {% endfor %}
            {% if pages.is_next == 1 %}
             <li>
                    <a href="{{ pages.url }}?&p={{ pages.total_pages }}&keyword={{ cont }}" ><span>尾页</span></a>
             </li>
            {%  endif %}
        </ul>
    </div>
</div>


    </div>
{% endblock %}
{% block Tag %}
    <div class="widget widget_sentence">
        <h3>标签云</h3>
        <div class="widget-sentence-content">
            <ul class="plinks ptags">
                {#直接 管道符 进行切片 和 倒序#}
                {% for tag in cate_obj.taginfo_set.all|slice:':10:-1' %}
                    <li><a href="{% url 'list' cate_obj.path_name %}?tag={{ tag.id }}" title="{{ tag.name }}"
                           draggable="false">{{ tag.name }} <span class="badge">{{ tag.article_set.count }}</span></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}
{% block TongJi %}
{% endblock %}

templates/search_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    搜索内容列表页
{% endblock %}
{% block content %}
    <div class="content">
            <div class="title">
                <h3 style="line-height: 1.3">搜索到相关{{ cont }}内容如下：</h3>
            </div>

            {% for art in all_articles %}
                <article class="excerpt excerpt-{{ forloop.counter }}"><a class="focus" href="{% url 'detail' art.id %}"
                                                                          title="{{ art.title }}" target="_blank"><img
                        class="thumb" data-original="{{ MEDIA_URL }}{{ art.image }}"
                        src="http://127.0.0.1:8000/static/images/timg.jpg" alt="{{ art.title }}"
                        style="display: inline;"> </a>
                    <header><a class="cat" href="{% url 'list' art.category.path_name %}" title="{{ art.category.name }}">{{ art.category.name }}<i></i></a>
                        <h2><a href="{% url 'detail' art.id %}" title="{{ art.title }}"
                               target="_blank">{{ art.title }}</a></h2>
                    </header>
                    <p class="meta">
                        <time class="time"><i class="glyphicon glyphicon-time"></i> {{ art.add_time }}</time>
                        <span class="views"><i class="glyphicon glyphicon-eye-open"></i>{{ art.click_num }}</span> <a
                            class="comment"
                            href="##comment"
                            title="评论"
                            target="_blank"><i
                            class="glyphicon glyphicon-comment"></i>{{ art.cont_num }}</a></p>
                    <p class="note">{{ art.desc }}</p>
                </article>
            {% endfor %}
            {% include 'pagenation.html' %}
            <nav class="pagination" style="display: none;">
                <ul>
                    <li class="prev-page"></li>
                    <li class="active"><span>1</span></li>
                    <li><a href="?page=2">2</a></li>
                    <li class="next-page"><a href="?page=2">下一页</a></li>
                    <li><span>共 2 页</span></li>
                </ul>
            </nav>
            </div>
{% endblock %}
{% block Tag %}
    <div class="widget widget_sentence">
        <h3>标签云</h3>
        <div class="widget-sentence-content">
            <ul class="plinks ptags">
{#                直接 管道符 进行切片 和 倒序#}
                {% for tag in all_tags %}
                    <li><a href="{% url 'list' tag.category.path_name %}?tag={{ tag.id }}" title="{{ tag.name }}"
                           draggable="false">{{ tag.name }} <span class="badge">{{ tag.article_set.count }}</span></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}
{% block TongJi %}
{% endblock %}